spring:
  profiles:
    active: dev
---
# 该配置注册到7001的eureka server
# 访问端口为8001，数据库为db01
# 配置环境为dev环境
server:
  port: 8001
mybatis:
  type-aliases-package: com.trd.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/*.xml
  configuration:
    cache-enabled: true
spring:
  profiles: dev                                           # dev环境
  application:
    name: microservicecloud-config-dept-remoteDev        # remote的Dev名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/clouddb01           # 数据库修改

#客户端注册进eureka服务列表
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: config-dept:8001         # Eureka的服务端的该微服务名Status名修改
    prefer-ip-address: true
info:
  app.name: microservice-SpringCloudConfig-DB01        # 数据库名修改
  company.name: www.trd.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
# 该配置注册到7002的eureka server
# 访问端口为8002，数据库为db02
# 配置环境为test环境
server:
  port: 8002
mybatis:
  type-aliases-package: com.trd.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/*.xml
  configuration:
    cache-enabled: true
spring:
  profiles: test                                           # test环境
  application:
    name: microservicecloud-config-dept-remoteTest          # remote的Test名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/clouddb02           # 数据库修改

#客户端注册进eureka服务列表
eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka
  instance:
    instance-id: config-dept:8002                 # Eureka的服务端的该微服务名Status名修改
    prefer-ip-address: true
info:
  app.name: microservice-SpringCloudConfig-DB02      # 数据库名修改
  company.name: www.trd.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$