# 保存为UTF-8编码
spring:
  profiles:
    active: dev
---
server:
  port: 8201
spring:
  profiles: dev    # dev环境
  application:
    name: microservicecloud-config-client-remoteDev       # remote仓库Dev环境名
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/erueka/   # 不用在hosts文件中映射，仅测试而已
---
server:
  port: 8202
spring:
  profiles: test     # test环境
  application:
    name: microservicecloud-config-client-remoteTest       # remote仓库Dev环境名
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7002/erueka/   # 不用在hosts文件中映射，仅测试而已
