spring:
  profiles:
    active: dev
---
# 配置环境为dev环境
# 该eureka server的port为7001，注册地址用7001的
server:
  port: 7001     #   注册中心占用7001端口,冒号后面必须要有空格
spring:
  profiles: dev
  application:
    name: microservicecloud-config-eureka-server-remoteDev
eureka:
  instance:
    hostname: eureka7001.com         # eureka服务端的实例名称,本机注册就是localhost
  client:
    register-with-eureka: false      #   不向注册中心注册自己
    fetch-registry: false            #  不通过eureka获取注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
# 配置环境为test环境
# 该eureka server的port为7002，注册地址用7002的
spring:
  profiles: test
  application:
    name: microservicecloud-config-eureka-server-remoteTest
server:
  port: 7002
# eureka server 相关配置
eureka:
  instance:
    hostname: eureka7002.com         # eureka服务端的实例名称,本机注册就是localhost
  client:
    register-with-eureka: false      #   不向注册中心注册自己
    fetch-registry: false            #  不通过eureka获取注册信息
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/